[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache, max-age=0, must-revalidate"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "no-cache, max-age=0, must-revalidate"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "no-cache, max-age=0, must-revalidate"

[[headers]]
  for = "/storage/*"
  [headers.values]
    Cache-Control = "no-cache, max-age=0, must-revalidate"

[[headers]]
  for = "/stats/*"
  [headers.values]
    Cache-Control = "no-cache, max-age=0, must-revalidate"

[[headers]]
  for = "/export/*"
  [headers.values]
    Cache-Control = "no-cache, max-age=0, must-revalidate"
